services:
  postgres:
    image: postgres:17
    container_name: ulinda-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ulinda-network

  backend:
    build: 
      context: ./backend
    container_name: ulinda-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      ADMIN_SECRET: ${ADMIN_SECRET}
    ports:
      - "127.0.0.1:${BACKEND_PORT}:8080"
    depends_on:
      - postgres
    networks:
      - ulinda-network

  frontend:
    build:
      context: ./frontend
    container_name: ulinda-frontend
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - ulinda-network

volumes:
  postgres_data:

networks:
  ulinda-network:
    driver: bridge